
# 서브모듈에서 워크플로우 디스패치 되도록 했을 때 (서브모듈에서 createWorkflowDispatch 호출했을 때)
on:
  workflow_dispatch:
  
# 실행중인 레포지토리에 쓰기 권한 부여 (서브모듈을 최신으로 업데이트 후 commit, push 하기위해 필요)
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 현재 레포지토리(프로젝트 메인 레포지토리)로 체크아웃
      # - name: Check out lokalise branch
      - uses: actions/checkout@v4
        with:
          submodules: true # 서브모듈도 함께 가져옴
          token: ${{ secrets.KOCO_GITHUB_TOKEN }} # 서브모듈이 private 레포일 경우 접근을 위해 필요
      
      #서브모듈 최신 상태로 업데이트
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
            
      # 변경사항 메인레포에 커밋,푸시
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Success] complete update submodule"
